export const PRODUCT_DETAILS = [
    {
        "productID": "MSDELUXE",
        "productName": "DO",
        "colorOptions": "#0000FF,#2E8B57,#C0C0C0",
        "motor": "1000 WT / 1200 WT",
        "controller": "55 AH",
        "tyreDiameter": "3.75-12",
        "tyreType": "CEAT & RALSON & MRF",
        "weightWithoutBattery": null,
        "breakType": null,
        "roof": "METAL ROOF\n",
        "shocker": "43 MM",
        "seatingCapacity": "4+1",
        "bodyDimension": null,
        "charger": "AXIOM 18 A / MICROTECH 21A",
        "battery": "EASTMAN & MUHAO",
        "rim": "ALLOY RIM / IRON",
        "mileage": "100-120",
        "sideCover": null,
        "wiper": "12V-12\"-RUBBER WIPER",
        "converter": "20Amp-48/60V",
        "headLight": "HALOGEN / LED",
        "price": null,
        "features": null,
        "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643916/Movestone/Products_new/Deluxe/SEN_3645_xgjjov.jpg",
        "curtain": "UV-Resistant Polyester Canvas",
        "sideLookingGlass": "ROUND",
        "camera": "YES",
        "sensorLock": "YES",
        "rearShocker": "HYDRAULIC",
        "fireExtinguisher": "YES",
        "footMat": "YES",
        "fmSet": "YES",
        "taxiLight": "YES",
        "fan": "YES",
        "toolKit": "YES",
        "jackHandleSet": "YES",
        "passengerHandle": "YES",
        "stepnyCover": "YES",
        "fogLight": "YES",
        "category": "eRikshaw",
        "visible": "Y",
        "productPictureDetails": [
            {
                "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643908/Movestone/Products_new/Deluxe/SEN_3682_uil821.jpg",
                "id": 1
            },
            {
                "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643916/Movestone/Products_new/Deluxe/SEN_3645_xgjjov.jpg",
                "id": 2
            },
            {
                "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643924/Movestone/Products_new/Deluxe/SEN_3671_xd1dzx.jpg",
                "id": 16
            }
        ]
    },
    {
        "productID": "MSECOFLEXI",
        "productName": "YOU",
        "colorOptions": "#FF0000,#A9A9A9",
        "motor": "1000 WT / 1200 WT",
        "controller": "55 AH",
        "tyreDiameter": "3.75-12",
        "tyreType": "CEAT & RALSON & MRF",
        "weightWithoutBattery": null,
        "breakType": null,
        "roof": "METAL",
        "shocker": "43 MM",
        "seatingCapacity": "4+1",
        "bodyDimension": null,
        "charger": "AXIOM 18 A / MICROTECH 21A",
        "battery": "EASTMAN & MUHAO",
        "rim": "ALLOY RIM / IRON",
        "mileage": "100-120",
        "sideCover": null,
        "wiper": "12V-12\"-RUBBER WIPER",
        "converter": "20Amp-48/60V",
        "headLight": "HALOGEN / LED",
        "price": null,
        "features": null,
        "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643733/Movestone/Products_new/ECO%20FLEXI/SEN_3544_iubiuy.jpg",
        "curtain": "UV-Resistant Polyester Canvas",
        "sideLookingGlass": "ROUND",
        "camera": "NO",
        "sensorLock": "YES",
        "rearShocker": "HYDRAULIC",
        "fireExtinguisher": "YES",
        "footMat": "YES",
        "fmSet": "YES",
        "taxiLight": "YES",
        "fan": "YES",
        "toolKit": "YES",
        "jackHandleSet": "YES",
        "passengerHandle": "YES",
        "stepnyCover": "YES",
        "fogLight": "YES",
        "category": "eRikshaw",
        "visible": "Y",
        "productPictureDetails": [
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643733/Movestone/Products_new/ECO%20FLEXI/SEN_3544_iubiuy.jpg",
            "id": 3
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643721/Movestone/Products_new/ECO%20FLEXI/SEN_3571_xp3r11.jpg",
            "id": 4
          }
        ]
      },
      {
        "productID": "MSSUPERPLUS",
        "productName": "DO",
        "colorOptions": "#FF0000,#0000FF",
        "motor": "1000 WT / 1200 WT",
        "controller": "55 AH",
        "tyreDiameter": "3.75-12",
        "tyreType": "CEAT & RALSON & MRF",
        "weightWithoutBattery": null,
        "breakType": null,
        "roof": "METAL ROOF\n",
        "shocker": "43 MM",
        "seatingCapacity": "4+1",
        "bodyDimension": null,
        "charger": "AXIOM 18 A / MICROTECH 21A",
        "battery": "EASTMAN & MUHAO",
        "rim": "ALLOY RIM / IRON",
        "mileage": "100-120",
        "sideCover": null,
        "wiper": "12V-12\"-RUBBER WIPER",
        "converter": "20Amp-48/60V",
        "headLight": "HALOGEN / LED",
        "price": null,
        "features": null,
        "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719642741/Movestone/Products_new/SUPER%20PLUS/SEN_3590_bt9dmd.jpg",
        "curtain": "UV-Resistant Polyester Canvas",
        "sideLookingGlass": "ROUND",
        "camera": "YES",
        "sensorLock": "YES",
        "rearShocker": "HYDRAULIC",
        "fireExtinguisher": "YES",
        "footMat": "YES",
        "fmSet": "YES",
        "taxiLight": "YES",
        "fan": "YES",
        "toolKit": "YES",
        "jackHandleSet": "YES",
        "passengerHandle": "YES",
        "stepnyCover": "YES",
        "fogLight": "YES",
        "category": "eRikshaw",
        "visible": "Y",
        "productPictureDetails": [
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719642736/Movestone/Products_new/SUPER%20PLUS/SEN_3708_qnxvwk.jpg",
            "id": 5
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719642741/Movestone/Products_new/SUPER%20PLUS/SEN_3590_bt9dmd.jpg",
            "id": 6
          }
        ]
      },
      {
        "productID": "MSMAXFLEXI",
        "productName": "HOW",
        "colorOptions": "#C0C0C0,#2E8B57,#FF0000,#0000FF",
        "motor": "1000 WT / 1200 WT",
        "controller": "55 AH",
        "tyreDiameter": "3.75-12",
        "tyreType": "CEAT & RALSON & MRF",
        "weightWithoutBattery": null,
        "breakType": null,
        "roof": "METAL ROOF\n",
        "shocker": "43 MM",
        "seatingCapacity": "4+1",
        "bodyDimension": null,
        "charger": "AXIOM 18 A / MICROTECH 21A",
        "battery": "EASTMAN & MUHAO",
        "rim": "ALLOY RIM / IRON",
        "mileage": "100-120",
        "sideCover": null,
        "wiper": "12V-12\"-RUBBER WIPER",
        "converter": "20Amp-48/60V",
        "headLight": "HALOGEN / LED",
        "price": null,
        "features": null,
        "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643779/Movestone/Products_new/MAX%20FLEXI/SEN_3532_hojnb8.jpg",
        "curtain": "UV-Resistant Polyester Canvas",
        "sideLookingGlass": "ROUND",
        "camera": "NO",
        "sensorLock": "YES",
        "rearShocker": "HYDRAULIC",
        "fireExtinguisher": "YES",
        "footMat": "YES",
        "fmSet": "YES",
        "taxiLight": "YES",
        "fan": "YES",
        "toolKit": "YES",
        "jackHandleSet": "YES",
        "passengerHandle": "YES",
        "stepnyCover": "YES",
        "fogLight": "YES",
        "category": "eRikshaw",
        "visible": "Y",
        "productPictureDetails": [
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643790/Movestone/Products_new/MAX%20FLEXI/SEN_3512_ysp6by.jpg",
            "id": 7
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643785/Movestone/Products_new/MAX%20FLEXI/SEN_3518_dhk50z.jpg",
            "id": 8
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643779/Movestone/Products_new/MAX%20FLEXI/SEN_3532_hojnb8.jpg",
            "id": 9
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643762/Movestone/Products_new/MAX%20FLEXI/SEN_3496_mi7hzc.jpg",
            "id": 10
          }
        ]
      },
      {
        "productID": "MSECOSUPER",
        "productName": "HELLO",
        "colorOptions": "#008000,#FFD700,#0000FF,#0000FF,#A9A9A9",
        "motor": "1000 WT / 1200 WT",
        "controller": "55 AH",
        "tyreDiameter": "3.75-12",
        "tyreType": "CEAT & RALSON & MRF",
        "weightWithoutBattery": null,
        "breakType": null,
        "roof": "METAL",
        "shocker": "43 MM",
        "seatingCapacity": "4+1",
        "bodyDimension": null,
        "charger": "AXIOM 18 A / MICROTECH 21A",
        "battery": "EASTMAN & MUHAO",
        "rim": "ALLOY RIM / IRON",
        "mileage": "100-120",
        "sideCover": null,
        "wiper": "12V-12\"-RUBBER WIPER",
        "converter": "20Amp-48/60V",
        "headLight": "HALOGEN / LED",
        "price": null,
        "features": null,
        "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643622/Movestone/Products_new/ECO%20SS/SEN_3579_hmwqsq.jpg",
        "curtain": "UV-Resistant Polyester Canvas",
        "sideLookingGlass": "ROUND",
        "camera": "YES",
        "sensorLock": "YES",
        "rearShocker": "HYDRAULIC",
        "fireExtinguisher": "YES",
        "footMat": "YES",
        "fmSet": "YES",
        "taxiLight": "YES",
        "fan": "YES",
        "toolKit": "YES",
        "jackHandleSet": "YES",
        "passengerHandle": "YES",
        "stepnyCover": "YES",
        "fogLight": "YES",
        "category": "eRikshaw",
        "visible": "Y",
        "productPictureDetails": [
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643699/Movestone/Products_new/ECO%20SS/SEN_3626_kg7ewp.jpg",
            "id": 11
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643647/Movestone/Products_new/ECO%20SS/SEN_3636_mj8x81.jpg",
            "id": 12
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643634/Movestone/Products_new/ECO%20SS/SEN_3558_yldapm.jpg",
            "id": 13
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643634/Movestone/Products_new/ECO%20SS/SEN_3558_yldapm.jpg",
            "id": 14
          },
          {
            "productImageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643622/Movestone/Products_new/ECO%20SS/SEN_3579_hmwqsq.jpg",
            "id": 15
          }
        ]
      },
      {
        "productID": "IUI01",
        "productName": "HARSHIKESH",
        "colorOptions": "#0000FF,#2E8B57,#C0C0C0",
        "motor": "1000 WT / 1200 WT",
        "controller": "55 AH",
        "tyreDiameter": "3.75-12",
        "tyreType": "CEAT & RALSON & MRF",
        "weightWithoutBattery": null,
        "breakType": null,
        "roof": "METAL ROOF\n",
        "shocker": "43 MM",
        "seatingCapacity": "4+1",
        "bodyDimension": null,
        "charger": "AXIOM 18 A / MICROTECH 21A",
        "battery": "EASTMAN & MUHAO",
        "rim": "ALLOY RIM / IRON",
        "mileage": "100-120",
        "sideCover": null,
        "wiper": "12V-12\"-RUBBER WIPER",
        "converter": "20Amp-48/60V",
        "headLight": "HALOGEN / LED",
        "price": null,
        "features": null,
        "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643916/Movestone/Products_new/Deluxe/SEN_3645_xgjjov.jpg",
        "curtain": "UV-Resistant Polyester Canvas",
        "sideLookingGlass": "ROUND",
        "camera": "YES",
        "sensorLock": "YES",
        "rearShocker": "HYDRAULIC",
        "fireExtinguisher": "YES",
        "footMat": "YES",
        "fmSet": "YES",
        "taxiLight": "YES",
        "fan": "YES",
        "toolKit": "YES",
        "jackHandleSet": "YES",
        "passengerHandle": "YES",
        "stepnyCover": "YES",
        "fogLight": "YES",
        "category": "eRikshaw",
        "visible": "Y",
        "productPictureDetails": [
          {
            "productImageURL": "http://res.cloudinary.com/dkoftgwba/image/upload/v1726923756/vbeoylc7ryhzhac6rp5u.png",
            "id": 17
          },
          {
            "productImageURL": "http://res.cloudinary.com/dkoftgwba/image/upload/v1726923757/hztsenme0truoja5mi6n.png",
            "id": 18
          }
        ]
      }
]